# use the shared Yast defaults
inherit_from:
  /usr/share/YaST2/data/devtools/data/rubocop-0.71.0_yast_style.yml

# Offense count: 153
Metrics/AbcSize:
  Max: 304

# Offense count: 32
Metrics/BlockNesting:
  Max: 8

# Offense count: 29
# Configuration parameters: CountComments.
Metrics/ClassLength:
  Max: 1100


Metrics/ModuleLength:
  Max: 600

# Offense count: 88
Metrics/CyclomaticComplexity:
  Max: 57

# Offense count: 432
# Configuration parameters: AllowURI, URISchemes.
Metrics/LineLength:
  Max: 204

# Offense count: 201
# Configuration parameters: CountComments.
Metrics/MethodLength:
  Max: 431

# Offense count: 89
Metrics/PerceivedComplexity:
  Max: 63

# Offense count: 85
Style/Documentation:
  Enabled: false

# Offense count: 6
# Configuration parameters: Exclude.
Naming/FileName:
  Include:
    - src/lib/**/*.rb
  Exclude:
    - src/lib/installation/clients/*.rb

# Offense count: 179
# Configuration parameters: EnforcedStyle, SupportedStyles.
Naming/MethodName:
  Include:
   - src/lib/**/*.rb
  Exclude:
    - src/lib/installation/clients/*.rb

# Offense count: 22
# Configuration parameters: EnforcedStyle, SupportedStyles.
Naming/VariableName:
  Include:
    - src/lib/**/*.rb
  Exclude:
    - src/lib/installation/clients/*.rb

Naming/PredicateName:
  Exclude:
    # mocked Registration.is_registered?
    - test/lib/upgrade_repo_manager_test.rb

Style/FrozenStringLiteralComment:
  Enabled: false
